### PR TITLE
Allow headergroups having depth more than 1. Fixes #12

### LINKED ISSUE #12: Cannot read property 'sticky' of undefined when using depth more than 1
`react-table-sticky` fails with an error

```
Cannot read property 'sticky' of undefined
```
when using headergroups with depth having more than 1. 
```
{
  "id": "name_details_container",
  "Header": "Name Details",
  "sticky": "left",
  "Footer": "Name Details",
  "columns": [
    {
      "Header": "Name",
      "Footer": "Name",
      "columns": [
        {
          "Header": "First Name",
          "Footer": "First Name",
          "accessor": "firstName"
        },
        { 
          "Header": "Last Name", 
	  "Footer": "Last Name", 
          "accessor": "lastName" 
        }
      ]
    }
  ]
}

```
Following is a reproducible example: 

https://codesandbox.io/s/react-table-sticky-official-r4hjg?file=/src/App.js

### PR DESCRIPTION
**Pull request by hardikmodha**
Fixes #12.

Codesandbox: https://codesandbox.io/s/react-table-sticky-official-bkx1o?file=/src/App.js

It has both the examples 

1. Where column depth more than 1
2. Where column depth is === 1

### CODE REVIEW

**Comment by hardikmodha** [comment]
@GuillaumeJasmin Please take a look. Let me know if I need to add some tests around it.

**Comment by hardikmodha** [comment]
@GuillaumeJasmin Friendly Ping.

**Comment by GuillaumeJasmin** [comment]
Hi @hardikmodha 
Thanks for your contribution, sorry for late !
Your codesandbox doesn't work for me: horizontal scroll doesn't work.
Could you add a second table demo in the `demo/index.tsx` please ?
Thank you 🙂

**Comment by hardikmodha** [comment]
> Your codesandbox doesn't work for me: horizontal scroll doesn't work.

Is it because of my changes? I think it shouldn't affect,  the changes are working fine with my app. 

> Could you add a second table demo in the demo/index.tsx please ?

I just need to replace the column definitions only. Right?

**Comment by hardikmodha** [comment]
@GuillaumeJasmin I've updated the demo. Let me know if it works.

**Comment by GuillaumeJasmin** [comment]
Thank you for this PR
Fix is available as of `v1.1.3`

**Pull request merged**
